server:
  port: 11401

spring:
  profiles: peer2
  
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:11400/eureka/
    fetchRegistry: false
    registerWithEureka: false
  server: 
    enable-self-preservation: true
    renewalPercentThreshold: 0.49
    peer-node-read-timeout-ms: 1000